version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: qa_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questions
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa_app
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: /app/config/dev.yaml
      DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/questions?sslmode=disable"
    ports:
      - "8082:8082"

volumes:
  pg_data:
