env: "dev"

database:
  host: "qa_postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "questions"
  sslmode: "disable"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
